# Generated by Django 3.1.4 on 2021-02-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_shopping_cart', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
